# https://taskfile.dev

version: '3'

vars:
  MODE: '{{default "debug"}}'
  ODIN: odin

  DEBUG_FLAGS: >-
    -debug
    -sanitize:address
  RELEASE_FLAGS: >-
    -vet
    -o:size

  LULU_OUT: bin/lulu
  LULU_SRC: lulu

  CDECL_OUT: bin/cdecl
  CDECL_SRC: cdecl

  # I am aware this is incredibly ugly
  ODIN_SRC_GLOB: '{{ "{" }}.,{{.LULU_SRC}},{{.CDECL_SRC}}{{ "}" }}'
  ODIN_FLAGS: >-
    {{if eq .MODE "debug"}}{{.DEBUG_FLAGS}}{{end}}{{if eq .MODE "release"}}{{.RELEASE_FLAGS}}{{end}}
    -define:USE_CONSTANT_FOLDING=true
    -define:USE_READLINE=true
    -collection:lulu={{.LULU_SRC}}/

  LUA_SRC: lua/src

tasks:
  build:
    desc: Build the Lulu executable.
    cmds:
      - '{{.ODIN}} build . {{.ODIN_FLAGS}} -out:{{.LULU_OUT}}'
    sources:
      - '*.odin'
      - '{{.LULU_SRC}}/*.odin'

  # https://taskfile.dev/usage/#forwarding-cli-arguments-to-commands
  run:
    desc: Build the Lulu executable if needed, then run it.
    cmds:
      - task: build
      - '{{.LULU_OUT}} {{.CLI_ARGS}}'
    interactive: true

  build-cdecl:
    desc: Build the cdecl executable.
    cmds:
      - '{{.ODIN}} build {{.CDECL_SRC}} {{.ODIN_FLAGS}} -out:{{.CDECL_OUT}}'
    sources:
      - '{{.CDECL_SRC}}/*.odin'

  run-cdecl:
    desc: Build the cdecl executable if needed, then run it.
    cmds:
      - task: build-cdecl
      - '{{.CDECL_OUT}} {{.CLI_ARGS}}'
    interactive: true

  build-lua:
    desc: Build the local Lua executable unconditionally.
    cmds:
      - |
        cd ./lua
        make --always-make --jobs=8
        mv ./src/lua ../bin/
        mv ./src/luac ../bin/
        cd ..

  # lol
  # https://taskfile.dev/styleguide/#prefer-using-external-scripts-instead-of-multi-line-commands
  clean-lua:
    cmds:
      - |
        cd ./lua
        make clean
        cd ..

  fix-whitespace:
    desc: Remove trailing whitespace from all *.{odin,c,h} files.
    deps:
      - task: find-and-replace
        vars:
          VIM_PATTERN: '\s\+$'
          VIM_REPLACE: ''

  # https://github.com/crimeraaa/lulu/blob/16cf4f5d187546704e7f66c9c401d85c4a71b68a/Taskfile.yml#L95C8-L95C11
  find-and-replace:
    desc: Replace a pattern in all *.{odin,[ch]} files. Uses Vim syntax.
    vars:
      VIM: vim
      # Dissection:
      #   -e              Ex mode, used mainly for non-interactive file editing.
      #   -u NONE         Do not load '.vimrc' or 'init.vim' of any kind.
      #   -c <command>    Execute <command> after entering.
      #   -- <...>        Positional arguments: file names or globs thereof.
      VIM_FLAGS: >-
        -e
        -u NONE
        -c ':bufdo! %s/{{.VIM_PATTERN}}/{{.VIM_REPLACE}}/ge'
        -c ':xa'
    prompt: This command will potentially modify all *.odin files in '{{.ODIN_SRC_GLOB}}'. Continue?
    cmds:
      - '{{.VIM}} {{.VIM_FLAGS}} {{.ODIN_SRC_GLOB}}/*.odin {{.LUA_SRC}}/*.[ch]'
    requires:
      vars: [VIM_PATTERN, VIM_REPLACE]
    preconditions:
      - sh: command -v {{.VIM}}
