# https://taskfile.dev

version: '3'

vars:
  LUA_BIN: ../bin
  LUA_SRC: src

  LUA_OUT: '{{.LUA_BIN}}/lua'
  LUA_GLOB: '{{.LUA_SRC}}/*.[ch]'

tasks:
  build:
    desc: Build the local Lua executable if needed.
    cmds:
      - |
        make --always-make --jobs=8
        mv {{.LUA_SRC}}/lua {{.LUA_BIN}}/
        mv {{.LUA_SRC}}/luac {{.LUA_BIN}}/
        mv {{.LUA_SRC}}/liblua.a {{.LUA_BIN}}/
    sources:
      - '{{.LUA_GLOB}}'

  run:
    desc: Build the local Lua executable if needed, then run it.
    dir: '{{.TASKFILE_DIR}}/..'
    cmds:
      - task: build
      - '{{.LUA_OUT | replace "../" ""}} {{.CLI_ARGS}}'
    interactive: true

  clean:
    desc: Deletes object files and binaries that were created.
    cmds:
      - make clean
