local f = assert(io.open("tests/ascii.lua", 'w'))

local byte   = string.byte
local char   = string.char
local format = string.format

f:write("-- generated by ", arg[0], "\nlocal t ={\n")

local STEP = 4
for b = byte('a'), byte('z'), STEP do
    f:write('\t')
    for i = 0, STEP - 1 do
        -- Non-printable?
        if b + i > 126 then
            break
        end
        local c = char(b + i)
        f:write(format("%q, %q, ", c:upper(), c:lower()))
    end
    -- Overwrite the trailing whitespace.
    f:seek("cur", -1)
    f:write('\n')
end

f:write([[
}

print(#t)

for i,v in ipairs(t) do
    print(string.format("t[%i] = %q", i, v))
end
]])

f:close()
