print("true and false:", true and false, "expected:", false)
print("false and true:", false and true, "expected:", false)
print("false and nil: ", false and nil,  "expected:", false)
print("nil and false: ", nil and false,  "expected:", nil)

print("true or false: ", true or false, "expected:", true)
print("false or true: ", false or true, "expected:", true)
print("false or nil:  ", false or nil,  "expected:", nil)
print("nil or false:  ", nil or false,  "expected:", false)

print("true and false or nil: ", true and false or nil, "expected:", nil)
print("true and nil or false: ", true and nil or false, "expected:", false)
print("false and true or nil: ", false and true or nil, "expected:", nil)
print("false and nil or true: ", false and nil or true, "expected:", true)
print("nil and true or false: ", nil and true or false, "expected:", false)
print("nil and false or true: ", nil and false or true)
-- print("nil and false or true: ", nil and false or true, "expected:", true)
