# https://taskfile.dev

version: '3'

vars:
  CPP_MODE: '{{.MODE | default "debug"}}'
  CC:  clang
  CXX: clang++

  # Notes(2025-06-11):
  #   - We can `-rdynamic` so that all symbols are in the dynamic symbol table
  #     and can thus be resolved when calling `backtrace()`.
  #   - However, if you're using `addr2line` then you don't need it.
  #   - You will need the dynlib library in that case though.
  #
  # See:
  #   - https://stackoverflow.com/a/6934857
  #
  CC_DEBUG_FLAGS: >-
    -O0
    -g
    -fsanitize=address
    -DLULU_DEBUG=1
    -DLULU_DEBUG_PRINT_CODE
    -DLULU_DEBUG_TRACE_EXEC
    -ldl

  CC_RELEASE_FLAGS: >-
    -Werror
    -O2
    -g
  # -s

  CC_FLAGS: >-
    -Wall
    -Wextra
    -Wpedantic
  # -Wconversion

  # Notes(2025-06-11):
  #   - `-nostdinc++` just prevents us from including C++ standard ilbrary
  #     headers, like `<string>`.
  #   - The C standard library is still available to us though.
  #   - `-nostdlib++` however cannot be used if we enabled ASAN because it
  #     requires typeinfo which is only found in `libstdc++`.
  #
  CXX_FLAGS: >-
    -std=c++17
    {{.CC_FLAGS}}
    -DLULU_BUILD_ALL
    -nostdinc++
    {{if eq .CPP_MODE "debug"}}{{.CC_DEBUG_FLAGS}}{{else if eq .CPP_MODE "release"}}{{.CC_RELEASE_FLAGS}}{{end}}

  CPP_BIN: ../bin
  CPP_SRC: src

  CPP_OUT: '{{.CPP_BIN}}/{{.OUT}}'
  CPP_SHARED: '{{.CPP_BIN}}/liblulu.so'
  CPP_STATIC: '{{.CPP_BIN}}/liblulu.a'

  CPP_DEBUG_CMD: >-
    {{.CXX}}
    -xc++
    {{.CXX_FLAGS}}

  CPP_RELEASE_CMD: >-
    {{.CC}}
    -std=c89
    {{.CC_FLAGS}}
    {{.CC_RELEASE_FLAGS}}

  # If compiling in debug mode, we linked ASAN to the C++ shared library.
  # So we need to compile lulu.c as C++ with the same flags to ensure we link
  # the correct ASAN runtime.
  CPP_OUT_COMPILE_COMMAND: >-
    {{if eq .CPP_MODE "debug"}}{{.CPP_DEBUG_CMD}}{{else if eq .CPP_MODE "release"}}{{.CPP_RELEASE_CMD}}{{end}}
    -L{{.CPP_BIN}}
    -o {{.OUT}}
    {{.CPP_SRC}}/lulu.c
    -llulu

  CPP_GLOB: '{{.CPP_SRC}}/*.[ch]*'

  # Note:
  #   - Annoyingly, even with `-x` (print horizontally), `ls` STILL adds a
  #     newline after a certain column number limit.
  #   - We instead use `-1` so each entry is on its own line.
  #   - We then use `tr` to manipulate the output.
  #
  # See:
  #   - https://taskfile.dev/reference/schema/#variable
  #   - https://serverfault.com/a/105841
  #
  CPP_GLOB_1LINE:
    sh: ls -1 {{.CPP_GLOB}} | tr "\n" " "
  CPP_GLOB_CXX_SRC: '{{regexFindAll "[^\\s]+\\.cpp" .CPP_GLOB_1LINE -1 | join " "}}'

tasks:
  build:
    desc: Build the Lulu executable
    vars:
    requires:
      vars: [CPP_MODE, CPP_SRC, CXX_FLAGS, CC_DEBUG_FLAGS, CC_RELEASE_FLAGS]
    cmds:
      # - echo Building from '{{.TASK_DIR}}'

      # NOTE: -fvisibility=hidden does not export a global identifier/function
      # in the resulting shared library.
      - '{{.CXX}} {{.CXX_FLAGS}} -shared -fPIC -fvisibility=hidden -o {{.CPP_SHARED}} {{.CPP_GLOB_CXX_SRC}}'
      - '{{.CPP_OUT_COMPILE_COMMAND}}'
    sources:
      - '{{.CPP_GLOB}}'

  # https://taskfile.dev/usage/#forwarding-cli-arguments-to-commands
  run:
    desc: Build the Lulu executable if needed, then run it.
    dir: '{{.TASKFILE_DIR}}/..'
    cmds:
      - task: build
      - '{{.CPP_OUT | replace "../" ""}} {{.CLI_ARGS}}'
    interactive: true

  list:
    cmds:
      # - ls -1 {{.CPP_GLOB}}
      # - echo CWD={{.TASK_DIR}}

      # regex* functions: <pattern> <input> ...
      # regexFindAll: <pattern> <input> <count>
      - echo regexFindAll = {{regexFindAll "[^\\s.]+\\.cpp" .CPP_GLOB_1LINE -1 | join " "}}

      # regexReplaceAll: <pattern> <input> <replacement>
      - echo regexReplaceAll = {{regexReplaceAll "[^\\s]+\\.hpp" .CPP_GLOB_1LINE ""}}
    silent: true
