local i = 16
if i == -1 then print("Nothing!")
elseif i == 0 then print('0')
elseif i == 1 then print('1')
elseif i == 2 then print('2')
elseif i == 3 then print('3')
elseif i == 4 then print('4')
elseif i == 5 then print('5')
elseif i == 6 then print('6')
elseif i == 7 then print('7')
elseif i == 8 then print('8')
elseif i == 9 then print('9')
elseif i == 10 then print('10')
elseif i == 11 then print('11')
elseif i == 12 then print('12')
elseif i == 13 then print('13')
elseif i == 14 then print('14')
elseif i == 15 then print('15')
else print("Overflow!")
end